SuperblocksHQ/ethereum-studio

packages/editor/src/reducers/utils/fileUtils.ts

> Renaming HelloWorld.sol to /app/HelloWorld.sol returns "Invalid file or folder name"
Renaming HelloWorld.sol to app/HelloWorld.sol doesn't move it to app directory, but adds the forward slash as part of the file name instead
Moving files with renaming was replaced with drag & drop feature, but the forward slash issue, should be fixed in this PR.
EDIT: Also fixes ES-6,7 as the issue was there because of the wrong name validation

Fix: ES-32,6,7 - Folder/File name validation issues

---

packages/editor/src/components/projectEditor/panels/messagesPanel/MessagesPanel.tsx
packages/editor/src/components/projectEditor/panels/output/OutputPanel.tsx

When a new message is added in `Output` or  `Messages` panel, it auto scrolls to the bottom so the user doesn't have to scroll manually.

Add: ES-42 - Implement auto scroll in output & messages panels

---

packages/editor/src/components/toasts/index.tsx
packages/editor/src/epics/projects/renameProject.epic.ts
packages/editor/src/reducers/toast.reducer.ts

Fixes ES-22:
> Renaming project to contain special characters results in silent failure
While renaming project and including special characters, it would silently fail and it wouldn't be possible to rename the project anymore, until user reloads the application.
Steps to verify:
1. Open project
2. Rename project to `Patata` -> project should be renamed
3. Rename project to `/Illegal Patata` -> toast with error should appear
4. Rename project to `Banana` -> project should be successfully renamed.

Fix: ES-22 - Properly handle error while renaming project

---

packages/editor/src/actions/projects.actions.ts
packages/editor/src/epics/projects/environmentUpdate.epic.ts

Fixing ES-58 so that application does not crash on Opera without Metamask, where `window.web3` is available but `window.web3.eth` is not.

Fix ES-58, loading in Opera, without Metamask.

---

packages/editor/src/components/projectEditor/editors/contractConfigModal/ContractConfigModal.tsx
packages/editor/src/components/projectEditor/editors/contractConfigModal/constructorArgument.tsx
packages/editor/src/components/projectEditor/editors/contractConfigModal/constructorArgumentsList.tsx
packages/editor/src/components/projectEditor/editors/contractConfigModal/index.ts
packages/editor/src/models/contractAgrumentData.ts
packages/editor/src/models/state/contractConfigState.model.ts
packages/editor/src/reducers/contractConfig.reducer.ts
packages/editor/src/selectors/contractConfig.selectors.ts

Removes the option to add contract as argument inside the contract modal.
1. Click on configure button for any contract
2. Open dropdown to change type of argument
3. Verify that there is only `account`, `value` and `array` options
ES-57

ES-57 - Remove contract args from contract configuration modal

---

packages/editor/src/components/topbar/Topbar.tsx

**Issue:** 
> `The query string gets propagated to Share functionality since the address bar is never updated.`
**Fix:**
The url in share modal should now be correct, without any query string
**Verify:**
1. Open share modal (share button in topBar)
2. First url (Editor link) should read `http://localhost:4000/<projectId>` (in local environment)
@filippsen Please double check this one if it actually solves the same issue as in ES-35

ES-35 - Fix openFile query string propagating into share functionality

---

packages/editor/src/epics/compiler/compileContract.epic.ts

Removed the cleaning of the build folder every time we compile a contract. The original idea of this addition was to start from a clean state every time compiling but I just realized that in fact this has raised a number of issues: 
- When compiling the contract (and therefore removing the build folder) it would also revert the dappfile.json content. 
- Also if we have compiled another contract before, compiling a different one would cause the entire compilation/deployment info of the previous contract to disappear. 
None that I can think of as right now. 
1. Start from Hello World template
2. Compile, then Deploy to make sure the project is in a good starting condition
3. Go to Configure and rename it. Save.
4. Repeat the Compile action. Everything in the contract config should remain …

ES-4 - Removed clean build folder every time compiling

---

packages/editor/src/epics/projects/exportProject.epic.ts

Solves ES-8 and 48
- When exporting project, include empty folders
- When exporting project, ask user if export should include build folder
- Fix wrong name of exported file
1. Open up any project
2. Create an empty folder inside project
3. Navigate to Topbar menu (left top hamburger) -> click File - Export project
3.1 - Exported file should be named `$projectName_$currentTimeStamp`
3.2 - Exported file should include empty folders
3.3 - If user enters `Yes` on the prompt, exported file should include `build` folder
3.4 - If user enters `No` on prompt, exported file shouldn't include `build` folder

Fix: ES-8,48 - Several fixes for export project functionality

---

packages/editor/src/actions/transactions.actions.ts
packages/editor/src/components/projectEditor/panels/blockexplorer/transaction.tsx
packages/editor/src/epics/deployer/deployContract.epicLib.ts
packages/editor/src/models/transaction.model.ts
packages/editor/src/reducers/transactions.reducer.ts
packages/editor/src/reducers/transactionsLib/formatTransaction.ts

- Include constructor arguments in transactions
- Format gas price/cost correctly
1. Open Hello World project
2. Compile, deploy and open transaction panel
3. It should read as follows (if all variables are set to default):
`Constructor arguments: Hello World!`
`Gas Price: 1 GWei`
`Gas cost: 0.000308891 Ether`
Resolves #47
Resolves #46

Transaction panel gas format/constructor args

---

packages/editor/src/reducers/panes.reducer.ts

This PR addresses the issue of having a small flicker when quickly clicking on an already opened tab. The solution is to check when opening a file whether the file to be opened is already opened.
No more flicker.
Resolves #83

Fix flicker when opening file

---

packages/editor/src/components/superProvider/index.ts

The Superprovider should return the selected account for `getAccounts()` just as a vanilla provider does it.
From the dapp when using browser network, access `this.web3.eth.getAccounts()` to see one account returned.
Note that until issue #86 is solved, the previously selected account is returned.
Resolves #66

Provide the selected account for provider.getAccounts(). Issue #66

---

packages/editor/src/reducers/deployer.reducer.ts
packages/editor/src/reducers/deployerLib/normalizeContractArgs.ts

Allow construct argument of type account while deploying a contract. More info in #45 
1.  From Hello World
2. Change HelloWorld.sol to:
```
pragma solidity ^0.5.10;
contract HelloWorld {
address public message;
constructor(address initMessage) public {
message = initMessage;
}
}
```
3. Go to Configure
4. Change argument type from value to account, then Save
5. Compile and Deploy
6. Check Interact panel, click on the green button and it should return the address of an account
Resolves #45

Fix contract deployment with argument of type account

---

packages/editor/src/components/projectEditor/control/backend.js
packages/editor/src/components/projectEditor/control/item/dappfileItem.js
packages/editor/src/epics/account/createNewAccount.epic.ts
packages/editor/src/networks.ts
packages/editor/src/selectors/project.selectors.ts
packages/editor/templates/Coin/dappfile.json
packages/editor/templates/Crypto Pizzas/dappfile.json
packages/editor/templates/Empty Project/dappfile.json
packages/editor/templates/Hello World/dappfile.json

As pointed out by @filippsen, the removal of custom networks from the dappfiles of the projects can cause crashes in older projects, when the external networks are enables again. For this reason this PR reverts all changes in commit "remove all external networks" and only hides the external options in the UI.

Hide external networks

---

packages/editor/src/components/projectEditor/panels/preview/Preview.tsx

This fixes issue #86 and also another bug when the iframe content was not properly updated when selecting an account.
Not allowing accounts to be changed.
When user changes account, it will actually reflect in the dapp preview code. The user benefits in that it behaves as one would expect.
Can't say.
Access accounts from the dapp, such as `web3.eth.accounts` and `this.web3.eth.getAccounts(...)` and observe that when changing accounts it is no longer the previously selected account which is available in the dapp, but the actual chosen one.
Also the refresh button has to be hit, which is fixed now.
I verified that there are no regressions by staring promptly at the screen for at least 30 seconds.
Resolves #86

Fix #86 - Superprovider always fed with previously selected account

---

packages/editor/src/components/projectEditor/panels/messagesPanel/MessagesPanel.tsx
packages/editor/src/components/projectEditor/panels/output/OutputPanel.tsx

When trying to compile or deploy inside embedded Studio, it would unexpectedly scroll whole window, instead the Output panel itself. You can try it here, by compiling from any iframe:
https://superblocks.com/ethereum-studio/
This PR shall fix this.

Fix forced scroll inside embedded Studio

---

package-lock.json
packages/editor/package.json

Found a possible fix on [Stackoverflow](https://stackoverflow.com/questions/53535479/cors-policy-blocking-the-access-to-ethereum) and on the web3 library [github](https://github.com/ethereum/web3.js/issues/1802) page, so in this PR the web3 library is rolled back to 0.20.6.
Relates to #55. Needs verifications.

Try fixing custom network related cors issues

---

superblocks.yaml

Fix the build type when creating the docker image to be uploaded to the registry during the CI process. 
Currently, we are actually deploying the `build:dev` version!!

Fix build type when creating the docker image

---

packages/editor/src/components/projectEditor/panels/interact/items/abiItemList/functions/Payable.tsx
packages/editor/src/components/projectEditor/panels/interact/items/abiItemList/functions/style.less

This PR hides the transaction argument box for payable functions in case the function has no input arguments.
No arguments can be passed to payable functions without input arguments.
Resolves #125

Hide transaction argument box if none present

---

packages/editor/src/reducers/projects.reducer.ts

- This should fix the bug with renaming account, more info in #92 
1. Create a New Account from topbar dropdown (Select an Account)
2. Try to rename newly created Account1 to Patata
3. It should update properly in the dropdown of account selector
4. Try to rename the Account1 once again to Patata
5. It should also rename properly
Resolves #92

Fix renaming of account

---

packages/editor/src/epics/projects/loadProject.epic.ts
packages/editor/src/epics/projects/renameProject.epic.ts

- Injects title with project name after loading the project
Javi:
> Better recognize the currently open project when the tab is open
> Easy to find a given project when searching in the browser history
> As atm we don't have user accounts and a dashboard to save the user projects, it would help when saving the project as a bookmark (instead of having to manually change the name
1. Create `Hello World` project
2. Check if tab name reads `Hello World | Ethereum Studio`
3. Rename project to `Patata`
4. Check if tab name reads `Patata | Ethereum Studio`
Resolves #123

Inject title with project name

---

packages/editor/src/epics/preview/tryToDownload.epic.ts

As the creation of the exportable html is tied to the Preview window, this PR automatically opens the it when the download button is clicked, so that the html can be downloaded.
Close preview window and hit 'Download' from the menu. 
Resolves #116

Fix 'Download' button not working when preview window is closed

---

packages/editor/src/epics/compiler/initCompilation.epic.ts

Fix the forking of a project when trying to compile a project which does not belong to you. The main issue was that the `initCompilation` epic was wrongly assuming the action had a `files` property. 
With this method of forking, we simply pull the latest from the server and fork it. 
1. Open this project http://localhost:4000/5dd403dd7cbff7b64f2119ff?openFile=README.md
2. Expand the HelloWorld.sol file and try to compile it. 
3. The newly created projects should be correctly forked

Fixed compilation related fork

---

packages/editor/src/reducers/explorer.reducer.ts

Automatically expand the `app`, `contracts` folder or  any `.sol` file to make it dead obvious to see the compile/deploy actions. 
To be able to see straight away all the possible actions a given contract does have. 
Open any given project and see that both the app/folder and any .sol files included in this former folder are indeed expanded. 
This solves #175

Automatically expand the app/contracts folders and any .sol file in it

---

packages/editor/templates/Empty Project/README.md

A few people have asked how they can (potentially) add templates to the template  chooser. I don't think we want to add everything people suggest or the list will be very  long,  but  I thought I'd update the empty  project readme to explain what people could do next.
I'll also add something along these lines to the opening dialogue, and the new video.

Add details on how people can use empty template to create projects

---

packages/editor/src/components/accountSelector/accountsList.tsx
packages/editor/src/components/accountSelector/style.less
packages/editor/src/components/projectEditor/panels/preview/style.less
packages/editor/src/components/projectEditor/style-console.less
packages/editor/src/components/projectEditor/style.less

Fixed padding on the bottom of the browser, now it is not being cut anymore. When you click edit account name of the not selected account it will automatically open the text input and select an account. Removed the green line on the select account hover because I think it looks better that way.
<!--

Edit account name in one click

---

packages/editor/src/components/accountSelector/accountSelector.tsx
packages/editor/src/components/accountSelector/style.less

- This should fix the issue when clicking outside of the account selector component it wouldn't hide the component. It was working correctly, only problem was when clicking on the iframe - (browser preview) - it wouldn't hide it.
- Because the issue was due to the iframe, which doesn't have onClick events, I had to make the dropdown similar to modal. Meaning that there is now a wrapper component around it. So the drawback is that when clicking outside on the first click, it won't trigger the events, if any, it will just hide the account selector component.
1. Click on Account selector
2. Click anywhere but the account selector
3. It should hide the component
Resolves #208

Fix: Clicking outside of dropdown/menu should exit this component

---

packages/editor/templates/Crypto Pizzas/README.md
packages/editor/templates/Hello World/README.md
packages/editor/templates/Hello World/app/app.js
packages/editor/templates/Hello World/contracts/HelloWorld.sol

Refactored the Hello World template (primarily the README) based on the extensive feedback we received from a group of Ethereum developers.
See #234
See #234
Users must go to the project files to read the code vs. the README, however, that's intended & based on the feedback we received will improve UX.
Ran the project locally.
#234

Update Hello World template [Fixes #234]

---

packages/editor/templates/Coin/app/app.css
packages/editor/templates/Coin/app/app.html
packages/editor/templates/Coin/app/app.js
packages/editor/templates/Crypto Pizzas/app/app.css
packages/editor/templates/Crypto Pizzas/app/app.html
packages/editor/templates/Crypto Pizzas/app/app.js
packages/editor/templates/Hello World/app/app.css
packages/editor/templates/Hello World/app/app.html
packages/editor/templates/Hello World/app/app.js

This change updates some of the template `app.js` files to check if `Contract.address` is set before displaying any UI input elements. It also includes some html/css changes to hide input elements by default, and display a welcome message instead.
So far, I've only added updates  to Hello World and Crypto Pizza. If the community is ok with the approach of this PR, I'd be happy to update the Coin template as well.
I'm not sure if checking `Contract.address` is the best way to determine whether or not the contract has been deployed. I was (and still am) looking to see if there's any kind of event or Promise I can listen to and be notified when the contract is deployed. If anyone knows of such a way, please let me know.
However, checking `Contract.address` appears to work, so I thought I'd …

Hide UI inputs until contract is deployed 
