SuperblocksHQ/ethereum-studio

packages/editor/src/reducers/explorer.reducer.ts, packages/editor/src/reducers/explorerLib/addAndMergeChildItems.ts, packages/editor/src/reducers/explorerLib/index.ts
There was an issue with importing multiple files to the same folder. Before this fix, the folders would simply get replaced, this fix merges the content of the given folder.
Importing multiple contracts, does not break the dependencies of previously imported contracts.
Import multiple contracts belonging to the same folder and observe that the content is merged instead of replaced.
=> Import fix

packages/editor/src/components/modals/projectTemplateModal/templates/index.ts, packages/editor/templates/coin/README.md, packages/editor/templates/cryptoPizzas/README.md, packages/editor/templates/helloWorld/README.md, packages/editor/templates/helloWorld/app/app.js, packages/editor/templates/helloWorld/contracts/HelloWorld.sol
Update template descriptions and readmes.
=> Templates update

packages/editor/src/actions/projects.actions.ts, packages/editor/src/components/modals/projectTemplateModal/ProjectTemplateModal.tsx, packages/editor/src/components/projectEditor/panels/explorer/items/baseItem.tsx, packages/editor/src/components/projectEditor/panels/explorer/items/contractItem.tsx, packages/editor/src/components/projectEditor/panels/explorer/items/fileItem.tsx, packages/editor/src/components/topbar/menu/MenuDropdownDialog.tsx, packages/editor/src/components/topbar/menu/index.ts, packages/editor/src/epics/projects/exportProject.epic.ts, packages/editor/src/epics/projects/index.ts, packages/editor/src/global.d.ts
- Disable drag & drop on contract actions and dappfile
- Remove actions in topbar when no project is open
- Implement export project functionality
=> Few more fixes

packages/editor/src/components/modals/importFileModal/style.less, packages/editor/src/components/modals/preferencesModal/style.less, packages/editor/src/components/modals/projectTemplateModal/style.less, packages/editor/src/components/modals/shareModal/style.less, packages/editor/src/components/projectEditor/editors/accountConfigModal/account-env-list.less, packages/editor/src/components/projectEditor/editors/accountConfigModal/style.less, packages/editor/src/components/projectEditor/editors/contractConfigModal/ContractConfigModal.tsx, packages/editor/src/components/projectEditor/editors/contractConfigModal/style.less
Fixes all modals to have it's content scrollable instead of whole modal
[SP-257](https://superblocks.atlassian.net/secure/RapidBoard.jspa?rapidView=1&projectKey=SP&modal=detail&selectedIssue=SP-257)
=> Fix modals and it's overflow

packages/editor/src/reducers/preview.reducer.ts
This PR addresses an issue that deleting any of the js, css or html files in the app folder crashes the application.
=> Fix preview error, SP-256 -> ES-9

packages/editor/src/actions/panes.actions.ts, packages/editor/src/actions/projects.actions.ts, packages/editor/src/components/projectEditor/panes/editor/fileEditor.tsx, packages/editor/src/components/projectEditor/panes/index.ts, packages/editor/src/components/projectEditor/panes/panes.tsx, packages/editor/src/components/topbar/menu/MenuDropdownDialog.tsx, packages/editor/src/components/topbar/menu/index.ts, packages/editor/src/epics/panes/setUnsavedChanges.epic.ts, packages/editor/src/epics/projects/index.ts, packages/editor/src/epics/projects/saveProject.epic.ts, packages/editor/src/reducers/explorer.reducer.ts, packages/editor/src/reducers/panes.reducer.ts, packages/editor/src/selectors/panes.selectors.ts
Deleted the `save` functionality and restored functionality to the `save all` and `download` functions in the topbar / file tab.
=> Fix topbar actions, SP-274, ES-23

packages/editor/src/components/modals/projectTemplateModal/templates/index.ts
Corrects coin description to not mention ERC-20 contract
=> Correct Coin description text

packages/editor/src/components/toasts/index.tsx, packages/editor/src/epics/compiler/compileContract.epic.ts, packages/editor/src/reducers/toast.reducer.ts
- Fix `compileContract` epic to check if it's your project and fork it accordingly.
- Add toast "Forking project" to `CREATE_FORKED_PROJECT` action
1. Create a new project in incognito mode (any browser)
2. Copy paste the url of the project and open it up in normal mode
3. Try to compile project (left button in menu)
4. "Forking project" toast should appear and redirect you to a new forked project
Resolves #49
=> Fix compile contract forking

packages/editor/src/epics/deployer/deployContract.epicLib.ts, packages/editor/src/services/deployer/deployRunner.ts
This MR addresses two issues where the errors took place due to the MM wallet not being open or not being available.
Resolves #52 
Resolves #53 
Resolves ES-27, ES-28
=> Fix Metamask related issues

packages/editor/src/epics/deployer/deployContract.epic.ts
This PR solves an issue regarding a silent error during deployment.
Resolves #57 
Resolves ES-3
=> Silent deploy error fix

packages/editor/src/components/topbar/style.less
- Fix alignment of Open Studio button on Chrome/Opera
More info in #77 
Resolves #77
=> Fix Open Studio text alignment

packages/web-server/src/api/routers/robots-txt.router.ts
Update robots.txt to allow all
https://www.robotstxt.org/orig.html#format
Now search engines & social platforms can crawl, index & generate image previews of the site
https://github.com/SuperblocksHQ/ethereum-studio/issues/78
=> Allow all robots [Fixes #78]

packages/editor/src/epics/interact/sendTransaction.epic.ts
- Push new transactions from interact panel (for browser network, it was already working for external)
1. Compile and deploy Hello World to browser network
2. Open Interact panel from left side
3. Update message with the yellow button
4. Transaction should show up in the transaction's panel
Resolves #60
=> Fix: Transactions performed by Interact are not listed on Transactions History

packages/editor/src/components/projectEditor/panels/messagesPanel/MessagesPanel.tsx
Converting to locale string instead of string manipulations to print the date.
Open messages panel and observe the first message.
Resolves #74 
Resolves ES-65
=> fix output time

packages/editor/templates/Coin/app/app.js, packages/editor/templates/Crypto Pizzas/app/app.js, packages/editor/templates/Empty Project/app/app.js, packages/editor/templates/Hello World/app/app.js
Added some additional checks so that we don't get the undefined error in the console anymore with any of the projects.
Resolves #72
Resolves ES-52
=> Fix Contracts not defined issue

packages/editor/src/components/common/topbar/help/index.tsx
`In the help menu it should not say "Join our Community", it should instead say "Eth Docs Help".`
Resolves #67
=> Change "Join our Community" to say "Eth Docs Help"

packages/editor/src/components/projectEditor/control/backend.js, packages/editor/src/components/projectEditor/control/item/dappfileItem.js, packages/editor/src/epics/account/createNewAccount.epic.ts, packages/editor/src/networks.ts, packages/editor/templates/Coin/dappfile.json, packages/editor/templates/Crypto Pizzas/dappfile.json, packages/editor/templates/Empty Project/dappfile.json, packages/editor/templates/Hello World/dappfile.json
This PR removes all external networks from ETH Studio for release 1.
=> Remove all external networks

packages/editor/src/components/projectEditor/panels/output/OutputPanel.tsx, packages/editor/src/services/deployer/deploy.utils.ts
- Fix handling of error in interact panel
- Better error output in deployment
- Deployment
1. Open Coin template and add some arguments into contract from Contract configuration
2. _Compile_
3. _Deploy_
4. Output should end up with `Constructor arguments given are not valid. Too many/few or wrong types.` instead of `Constructor arguments given are not valid. Too many/few or wrong types. undefined`
- Interact
1. Open CryptoPizza, Compile/Deploy
2. Run the approve method from Interact panel with no parameters
3. Output should log out some error instead crashing the application
Resolves #89
=> Fix handling of error in interact and deployment

packages/editor/src/components/projectEditor/panes/editor/markdownPreview.tsx
Adds new option to `showdown` to open up links in a new tab
1. Create Hello World template
2. Try clicking on any link inside README's Markdown preview with left mouse click
3. Link should open in a new tab
Resolves #100
=> Open links in a new tab inside Markdown preview

packages/editor/src/components/common/topbar/newProject/newProjectDialog/index.tsx, packages/editor/src/components/modals/projectTemplateModal/ProjectTemplateModal.tsx
- Adds new text into Template select modal
First time use seems more welcoming than before
Resolves #69
=> Add Welcome text into Template select modal

packages/editor/src/components/projectEditor/panels/interact/items/abiItemList/functions/Transaction.tsx, packages/editor/src/components/projectEditor/panels/interact/style.less
- Fixes functions in Interact panel which don't have any parameters
- Fix selection of the text in Interact panel, it wasn't possible to select any text in Interact before, this should fix this
More info in #91 
Resolves #91
=> Fix function with no parameters in Interact panel

packages/editor/src/components/superProvider/index.ts
=> Fix vague if statement which erroneously interpretes nonce 0 as error

README.md
Minor README update - pretty self-explanatory :)
Resolves #99
=> Update README image & URL reference [Fixes #99]

packages/editor/src/components/superProvider/index.ts, packages/editor/templates/Crypto Pizzas/contracts/CryptoPizza.sol
- Adds new error handler to improve message when trying to create Pizza with name that already exists
- Improved message so the user can know what exactly has happened
1. Create CryptoPizza
2. Compile/Deploy
3. Create pizza from preview or interact panel with name `patata`
4. Repeat step 3 and observe new error message appear
=> Improve error handling within CryptoPizza template

packages/editor/public/index.html
- Removes unnecessary load of the intercom script as it wasn't being used anyway
- Check network tab and there shouldn't be any mention of Intercom being loaded
=> Remove intercom script

packages/editor/src/actions/transactions.actions.ts, packages/editor/src/epics/interact/sendTransaction.epic.ts, packages/editor/src/epics/transactions/checkSentTransactions.epic.ts, packages/editor/src/epics/transactions/index.ts
This PR adds a new epic which is used to periodically check the blockchain in case there are unconfirmed transactions. It also takes care of the case, when the transaction succeeded, but the execution threw an error.
Transactions with failed execution don't stay in pending state indefinately.
From CryptoPizza template try making an obviously wrong transaction, like burning a pizza, which doesn't belong to you.
Resolves #88
=> Fix infinite pending transaction

package-lock.json, packages/editor/package.json
Reverts SuperblocksHQ/ethereum-studio#96
=> Revert "Try fixing custom network related cors issues"

packages/editor/src/actions/interact.actions.ts, packages/editor/src/components/projectEditor/panels/interact/items/abiItemList/AbiList.tsx, packages/editor/src/components/projectEditor/panels/interact/items/abiItemList/functions/Payable.tsx, packages/editor/src/components/projectEditor/panels/interact/items/abiItemList/functions/style.less, packages/editor/src/components/projectEditor/panels/interact/items/abiItemList/index.ts
This PR adds the value field to the interaction menu for payable transactions.
Payable transactions work again.
Resolves some of the items listed in #105
=> Fix payable transactions

packages/editor/src/actions/interact.actions.ts, packages/editor/src/components/projectEditor/panels/interact/items/abiItemList/AbiList.tsx, packages/editor/src/components/projectEditor/panels/interact/items/abiItemList/index.ts, packages/editor/src/epics/interact/getConstant.epic.ts, packages/editor/src/epics/interact/sendTransaction.epic.ts
This should fix interacting with functions which are overloaded. I've noticed during testing that not even `Constants` were problematic, but `Payable` and `Transaction` functions as well. This should fix it. More info in #114 
Example contract file:
```
pragma solidity ^0.5.10;
contract MyContract {
string public a;
uint public b;
// Constant
function test1(string memory _a) public pure returns(string memory) {
return _a;
}
function test1(string memory _a, uint _b) public pure returns(string memory, uint) {
return (_a, _b);
}
// Transaction
function test2(string memory _a) public {
a = _a;
}
function test2(string memory _a, uint _b) public {
a = _a;
b = _b;
}
// Payable
function test3(string memory _a) public payable {
a = _a;
}
function test3(string memory _a, uint _b) public payable {
a …
```
=> Fix overloaded functions in Interact panel

packages/editor/src/components/projectEditor/panels/messagesPanel/MessagesPanel.tsx, packages/editor/src/components/projectEditor/panels/output/OutputPanel.tsx
- This should fix the unexpected scroll inside iframe, more info in #138 
Resolves #138
=> Fix unexpected scroll inside iframe

packages/editor/src/components/modals/projectTemplateModal/ProjectTemplateModal.tsx
Update intro video to YouTube link
Current link is broken
#130
=> Update intro video to YouTube link [Fixes #130]

packages/editor/src/components/common/errorMessage/index.js, packages/editor/src/components/projectEditor/editors/accountConfigModal/AccountConfigModal.tsx, packages/editor/src/components/projectEditor/editors/accountConfigModal/index.ts, packages/editor/src/validations/index.ts
- Adds simple account name validation while updating the name to ensure that we have accounts with unique names
- Adds validation to disallow unique characters for accounts
Testing out #133 should be enough to verify the functionality as the other issues shouldn't be possible to reproduce
Resolves #133
Resolves #134 
Resolves #135
=> Add account name validation

packages/editor/src/actions/compiler.actions.ts, packages/editor/src/actions/projects.actions.ts, packages/editor/src/epics/compiler/compileContract.epic.ts, packages/editor/src/epics/compiler/index.ts, packages/editor/src/epics/compiler/initCompilation.epic.ts, packages/editor/src/epics/panes/setUnsavedChanges.epic.ts, packages/editor/src/epics/projects/saveProject.epic.ts, packages/editor/src/models/state/explorer.model.ts, packages/editor/src/reducers/compiler.reducer.ts, packages/editor/src/reducers/explorer.reducer.ts, packages/editor/src/selectors/explorer.selectors.ts
This PR automatically saves the state of the project before compilation, so it's always the latest state that is being used during compilation.
Resolves #97
=> Implement autosave when compiling

packages/editor/src/components/projectEditor/editors/contractConfigModal/ContractConfigModal.tsx, packages/editor/src/components/projectEditor/editors/contractConfigModal/style.less, packages/editor/src/epics/deployer/deployContract.epicLib.ts, packages/editor/src/epics/explorer/updateDappfile.epic.ts, packages/editor/src/models/contractConfiguration.model.ts, packages/editor/src/reducers/contractConfig.reducer.ts, packages/editor/src/reducers/deployer.reducer.ts, packages/editor/src/reducers/deployerLib/getContractValue.ts, packages/editor/src/services/deployer/deployRunner.ts
- Adds new constructor option in Contract modal for payable contracts, more info in #118 
It should now be possible to deploy contract with constructor which is payable  `constructor() public payable { ... }`
The option for value in Contract modal will be always visible whether or not the constructor is payable. But it shouldn't break anything, though it can be confusing.
Example snippet code:
```
uint public value;
constructor() public payable {
require(msg.value == 10000 wei, "10000 wei initial funding required");
value = msg.value;
}
```
1. Create contract with the example code or similar one
2. Go to `Configure` settings of Contract
3. Locate `Value` input and add value of `10000` -> save
4. Compile and Deploy -> it should succeed
5. Go to Interact panel and check if value Constant …
=> Add functionality for payable constructor

packages/editor/src/actions/explorer.actions.ts, packages/editor/src/epics/explorer/moveItem.epic.ts, packages/editor/src/epics/explorer/updateDappfile.epic.ts
This PR addresses the issue of smart contract arguments being lost during moving files. The issue was that simply the arguments weren't copied when the new entry in the dappfile was created.
As contracts in the dappfile are only identified by name and not by id, some bugs might occur when moving files with the same name.
Resolves #93
=> Fix disappearing args

packages/editor/src/components/modals/projectTemplateModal/ProjectTemplateModal.tsx
We made updates to the tutorial video, this is the updated link.
Fixes the currently broken link.
https://github.com/SuperblocksHQ/ethereum-studio/issues/130
=> Update Youtube link

packages/editor/templates/Coin/README.md, packages/editor/templates/Hello World/README.md
Closes #167 I think I got them all, also updated Kauri posts
=> Remove network references

packages/editor/templates/Crypto Pizzas/README.md
Contracts library renamed to OpenZeppelin Contracts
https://forum.openzeppelin.com/t/we-re-changing-the-company-name-from-zeppelin-to-openzeppelin/1047
Updated CryptoPizza README to reflect the name.
N/A
Ensure developers can easily find OpenZeppelin Contracts
Text only change
Viewed CryptoPizza README
N/A
=> Update Zeppelin to OpenZeppelin in CryptoPizza README

packages/editor/src/components/common/topbar/help/index.tsx
This branch focuses on fixes for: https://github.com/SuperblocksHQ/ethereum-studio/issues/178
I just removed two links from `index.tsx` which @javier-tarazaga said we do not need anymore
=> removed unncessary links

Dockerfile, package.json, packages/editor/package.json, packages/editor/scripts/env.sh
Hopefully the final batch of solutions for some of the problems experienced in staging due to the injection of vars.
=> Even more fixes for the Injected env var logic

Dockerfile
=> Fix env variables injection

packages/editor/templates/Hello World/README.md, packages/editor/templates/Hello World/app/app.html, packages/editor/templates/Hello World/app/app.js, packages/editor/templates/Hello World/contracts/HelloWorld.sol
Addresses some comments in https://github.com/SuperblocksHQ/ethereum-studio/issues/170 by bringing code and readmes in sync and adding more comments inline of code.
=> Bring examples up to date and add more code comments

packages/editor/templates/Coin/README.md, packages/editor/templates/Coin/app/app.html, packages/editor/templates/Coin/app/app.js, packages/editor/templates/Coin/contracts/Coin.sol
Updates to coin template to add more detail to code comments and ensure code and docs are in sync.
Part of #170
=> Updates to coin example

packages/editor/templates/Coin/README.md, packages/editor/templates/Crypto Pizzas/README.md, packages/editor/templates/Empty Project/README.md, packages/editor/templates/Hello World/README.md
Update to README instructions to solve #191
#191
=> Update README to match new UI [Fixes #191]

packages/editor/src/components/projectEditor/panels/explorer/items/baseItem.tsx, packages/editor/src/components/projectEditor/panels/explorer/items/contractItem.tsx, packages/editor/src/components/projectEditor/panels/explorer/items/fileItem.tsx, packages/editor/src/components/projectEditor/panels/explorer/items/folderItem.tsx, packages/editor/src/components/projectEditor/panels/explorer/items/style.less
Fixes the position of context menu when performing right click on any item in file explorer.
Due to being in small container I've added a detection of mouse position so the context menu appears relative to the mouse position
Makes it usable again
None I can think of
1. Open up any project
2. Right click on any file inside the file explorer (on the left side)
3. Context menu should show up and all actions should be visible
Resolves #200
=> Fix context menu position in file explorer

packages/editor/src/components/modals/projectTemplateModal/ProjectTemplateModal.tsx
Update YouTube video (old link is dead)
=> Update YouTube video

packages/editor/src/components/projectEditor/editors/contractConfigModal/ContractConfigModal.tsx, packages/editor/src/components/projectEditor/editors/contractConfigModal/constructorArgument.tsx, packages/editor/src/components/projectEditor/editors/contractConfigModal/constructorArgumentsList.tsx, packages/editor/src/epics/contractConfiguration/index.ts, packages/editor/src/epics/contractConfiguration/updateContractConfig.epic.ts
These changes allow for manual addition of arguments to the constructor of the smart contracts and they automatically update in the configure dialog now
This fixes #171
=> Configure dialog fix

packages/editor/package.json, packages/editor/templates/Crypto Pizzas/README.md, packages/editor/templates/Crypto Pizzas/contracts/CryptoPizza.sol
This PR updates the CryptoPizza readme, and adds comments inline in the contract file. It also updates the OpenZeppelin dependency.
Also, I realised that I had parked adding instructions on the JavaScript as it was a big task. This is now in progress, but it will take a little while, so let's get this merged in the meantime.
Closes #165 amongst others (partially)
=> Update comments and OpenZeppelin dependencies for CryptoPizza template

packages/editor/src/epics/contractConfiguration/updateContractConfig.epic.ts
Since some of our templates do not have constructor, I added a check for empty constructor in `updateContractConfig.epic`, this will allow to compile and deploy said templates
=> small fix for cryptopizza template

package-lock.json, packages/editor/scripts/postinstall.js
Fixed `postinstall.js` script which will allow for proper generation of templates and openzeppelin.json file, it should also fix the build error in the superblocks platform. 
this PR seems to have broken it, just for reference purposes
#199
=> fixed postinstall script

packages/editor/src/components/projectEditor/ProjectEditor.tsx, packages/editor/src/components/projectEditor/index.ts
Console now opens automatically on the first output it receives
#209
=> console opens automatically on the first output

packages/editor/templates/Hello World/README.md, packages/editor/templates/Hello World/app/app.css, packages/editor/templates/Hello World/app/app.html, packages/editor/templates/Hello World/app/app.js
Add input form to HelloWorld template UI & functionality in app.js to update the contract storage.
Allows the user to interact with contract via the dapp UI interface.
Tested locally & in production.
#205
=> Add input form to HelloWorld template [Fixes #205]

packages/editor/src/components/projectEditor/panes/editor/style-markdown-preview.less
None
Less jarring code style contrast.
Code snippets in READMEs may be less obvious.
Local dev.
#248
=> Update code element styles [Fixes #248]

packages/editor/public/index.html
Adding GA so we can have some more information about site referrals and from where people are coming when opening the tool. 
Adding a bit more information to help us out to carve a better product
Atm you can't turn it off in the settings dialog. To do so will require a bit more work.
=> Simply added Google Analytics

packages/editor/src/actions/transactions.actions.ts, packages/editor/src/components/projectEditor/panels/blockexplorer/transaction.tsx, packages/editor/src/components/projectEditor/panels/preview/Preview.tsx, packages/editor/src/components/projectEditor/panels/preview/index.ts, packages/editor/src/components/superProvider/index.ts, packages/editor/src/epics/deployer/deployContract.epicLib.ts, packages/editor/src/epics/interact/sendTransaction.epic.ts, packages/editor/src/epics/transactions/index.ts, packages/editor/src/epics/transactions/updateTransaction.epic.ts, packages/editor/src/epics/transactions/updateTransactionFail.epic.ts, packages/editor/src/epics/transactions/updateTransactionState.epic.ts, packages/editor/src/models/addTransaction.model.ts, packages/editor/src/models/formatTransaction.model.ts, packages/editor/src/models/index.ts, packages/editor/src/models/transaction.model.ts, packages/editor/src/models/updateTransactionFail.model.ts, packages/editor/src/reducers/transactions.reducer.ts, packages/editor/src/reducers/transactionsLib/formatTransaction.ts, packages/editor/src/services/preview.service.ts
These code changes should fix the bug when mint function from the Token template is called when the account is not an owner. It will display an error message in the console and the failed transaction will be shown in the transactions tab. Also, in transactions tab the appropriate label for arguments should be displayed now.
#260 #261
=> Fix coin mint

packages/editor/src/components/modals/projectTemplateModal/templates/index.ts, packages/editor/templates/Crypto Pizzas/README.md, packages/editor/templates/Crypto Pizzas/app/app.js, packages/editor/templates/Crypto Pizzas/contracts/CryptoPizza.sol, packages/editor/templates/Token/README.md, packages/editor/templates/Token/app/app.js
Revamp the "CryptoPizza" template. See #246 for list of changes.
See #246
See #246
- Users must go to the project files to read the code vs. the README, however, that's intended & based on the feedback we received will improve UX.
Ran & tested project locally.
#246
=> Revamp CryptoPizza template [Fixes #246]

packages/editor/src/actions/panes.actions.ts, packages/editor/src/components/projectEditor/panes/editor/fileEditor.tsx, packages/editor/src/components/projectEditor/panes/editor/index.ts, packages/editor/src/components/projectEditor/panes/editor/markdownPreview.tsx, packages/editor/src/components/projectEditor/panes/panes.tsx, packages/editor/src/epics/deployer/deployContract.epicLib.ts, packages/editor/src/epics/interact/sendTransaction.epic.ts, packages/editor/src/epics/panes/outboundLinkClick.epic.ts, packages/editor/src/epics/transactions/updateTransaction.epic.ts, packages/editor/src/epics/transactions/updateTransactionState.epic.ts, packages/editor/templates/Crypto Pizzas/dappfile.json, packages/editor/templates/Empty Project/dappfile.json, packages/editor/templates/Hello World/dappfile.json
Added new event trackers for certain analytics, such as `SEND_TRANSACTION` and `OUTBOUND_LINK_CLICK`, also updated the old `CONTRACT_DEPLOYED` event.
#256
=> Add event tracking
